# This script can be used to bootstrap development dependencies.

version: "3.8"

services:

  cryptofolio-postgres:
    image: postgres:13.1
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_USER=cryptofolio
      - POSTGRES_PASSWORD=Pass@word1
      - POSTGRES_DB=cryptofolio
    restart: unless-stopped

  cryptofolio-kafka:
    image: lensesio/fast-data-dev:latest
    ports:
      - "2181:2181"
      - "3030:3030"
      - "8081-8083:8081-8083"
      - "9581-9585:9581-9585"
      - "9092:9092"
    environment:
      - ADV_HOST=localhost
    restart: unless-stopped

  cryptofolio-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  cryptofolio-redis:
    image: redis:6.2.4
    ports:
        "6379:6379"
