{{- if .Values.api.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cryptofolio-api.serviceAccountName" . }}
  labels:
    {{- include "cryptofolio-api.labels" . | nindent 4 }}
  {{- with .Values.api.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.api.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

---

{{- if .Values.app.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cryptofolio-app.serviceAccountName" . }}
  labels:
    {{- include "cryptofolio-app.labels" . | nindent 4 }}
  {{- with .Values.app.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.app.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

---

{{- if .Values.jobs.collector.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cryptofolio-collector-job.serviceAccountName" . }}
  labels:
    {{- include "cryptofolio-collector-job.labels" . | nindent 4 }}
  {{- with .Values.jobs.collector.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.jobs.collector.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

---

{{- if .Values.jobs.handlers.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cryptofolio-handlers-job.serviceAccountName" . }}
  labels:
    {{- include "cryptofolio-handlers-job.labels" . | nindent 4 }}
  {{- with .Values.jobs.handlers.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.jobs.handlers.serviceAccount.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}